steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
images:
  - '${_IMAGE_NAME}:${_IMAGE_TAG}'
